<?xml version="1.0" encoding="UTF-8"?><testrun name="CardBusinnesTest" project="CreditCardEJB" tests="5" started="5" failures="1" errors="0" ignored="0">
  <testsuite name="co.com.techandsolve.creditcard.business.CardBusinnesTest" time="0.0">
    <testcase name="cuandoEsMasDe_700M_AgregarBonificar_10M" classname="co.com.techandsolve.creditcard.business.CardBusinnesTest" time="0.0"/>
    <testcase name="cuandoTieneBonos_noAgregarBonificacion" classname="co.com.techandsolve.creditcard.business.CardBusinnesTest" time="0.0"/>
    <testcase name="cuandoEsMasDe_1Mll_AgregarBonificar_20M" classname="co.com.techandsolve.creditcard.business.CardBusinnesTest" time="0.0"/>
    <testcase name="cuandoEstaBloqueadaUnaTarjenta" classname="co.com.techandsolve.creditcard.business.CardBusinnesTest" time="0.0"/>
    <testcase name="cuandoSeCreaUnaTarjeta" classname="co.com.techandsolve.creditcard.business.CardBusinnesTest" time="0.0">
      <failure>Wanted but not invoked:
cardBean.create(
    co.com.techandsolve.creditcard.entities.Card@1b48197
);
-&gt; at co.com.techandsolve.creditcard.business.CardBusinnesTest.cuandoSeCreaUnaTarjeta(CardBusinnesTest.java:136)
Actually, there were zero interactions with this mock.

	at co.com.techandsolve.creditcard.business.CardBusinnesTest.cuandoSeCreaUnaTarjeta(CardBusinnesTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
  </testsuite>
</testrun>
